#!/usr/bin/env node
/**
 * warroom-install.mjs — install, check and roll back the `warroom` launcher.
 *
 * POSTURE: `check` is READ-ONLY and blocks nothing. `install` and `rollback`
 * write, and refuse rather than guess whenever they find something they did not
 * put there.
 *
 * The problem this exists to end: `~/bin/<project>` was a ~2,765-line program
 * copied per project. Fifteen copies had drifted into eight generations with no
 * update path, so every improvement paid back in one project out of fifteen.
 *
 * Safety rules, in the order they are enforced. Each exists because the failure
 * it prevents is silent and expensive:
 *
 *   1. HARD LINK        — refuse outright. Writing through a hard link mutates
 *                         every other name for that inode.
 *   2. SYMLINK          — preserve the link, write to its resolved target.
 *                         Clobbering it would silently detach the user's layout.
 *   3. LOCAL EDIT       — if a file's hash differs from what we recorded at
 *                         install, someone edited it. Refuse; do not merge.
 *   4. BACKUP FIRST     — no file is overwritten before its bytes are stored
 *                         under a content hash.
 *   5. VALIDATE         — `bash -n` the result. A syntax error in the launcher
 *                         means no session can start.
 *   6. ATOMIC-ISH       — plan every write, refuse on ANY problem, then apply.
 *                         A validation failure never leaves a half-updated
 *                         install (the `installation_modified` guard).
 *
 * The structural boundary: this program writes `~/bin/<session>` and
 * `~/.warroom/`. It NEVER writes `<repo>/.warroom.yml` or anything else inside
 * a project. Generated content and project-owned content never share a
 * destination, so an update cannot clobber a customization.
 *
 * Usage:
 *   node scripts/warroom-install.mjs check [--config <path>]...   # read-only
 *   node scripts/warroom-install.mjs install --config <path> [--force]
 *   node scripts/warroom-install.mjs rollback --session <name>
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const HOME = os.homedir();
const WARROOM_HOME = path.join(HOME, '.warroom');
const MANIFEST = path.join(WARROOM_HOME, 'manifest.json');
const BACKUPS = path.join(WARROOM_HOME, 'backups');
const PROGRAM_SRC = path.join(REPO, 'bin', 'warroom');

const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
const sha256File = (p) => sha256(fs.readFileSync(p));

function readManifest() {
  try {
    return JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  } catch {
    return { version: 1, installs: {} };
  }
}

function writeManifest(m) {
  fs.mkdirSync(WARROOM_HOME, { recursive: true });
  fs.writeFileSync(MANIFEST, `${JSON.stringify(m, null, 2)}\n`);
}

/** Flat `key: value` reader — same contract as the shell side. */
function readConfig(file) {
  const text = fs.readFileSync(file, 'utf8');
  const get = (key) => {
    const m = new RegExp(`^\\s*${key}\\s*:\\s*(.*)$`, 'm').exec(text);
    if (!m) return '';
    let v = m[1].replace(/\s*#.*$/, '').trim().replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1');
    if (v.startsWith('~')) v = HOME + v.slice(1);
    return v;
  };
  return { session: get('session'), projectDir: get('project_dir'), file: path.resolve(file) };
}

const shimFor = (session, configPath) => `#!/bin/bash
# ${session} — war-room launcher shim.
#
# Generated by scripts/warroom-install.mjs. Do NOT edit: an update will detect
# the change and refuse, which is the intended behaviour but costs you a
# conflict to resolve. Project settings belong in the config file below.
exec "${path.join(WARROOM_HOME, 'bin', 'warroom')}" --config "${configPath}" "$@"
`;

/** Inspect a destination without writing. Returns the reason it cannot be written, or null. */
function inspect(dest, expectedHash) {
  if (!fs.existsSync(dest)) return { state: 'new', blocker: null, realPath: dest };

  const lst = fs.lstatSync(dest);
  const realPath = lst.isSymbolicLink() ? fs.realpathSync(dest) : dest;
  const st = fs.statSync(dest);

  if (st.nlink > 1) {
    return {
      state: 'hardlink',
      realPath,
      blocker: `${dest} has ${st.nlink} hard links — writing it would mutate every other name for that inode. Refusing.`,
    };
  }

  const current = sha256File(realPath);
  if (expectedHash && current !== expectedHash) {
    return {
      state: 'modified',
      realPath,
      current,
      blocker: `${dest} was modified since install (sha ${current.slice(0, 12)} != recorded ${expectedHash.slice(0, 12)}). Refusing to overwrite. Re-run with --force to discard the local edit.`,
    };
  }
  if (!expectedHash) {
    return {
      state: 'unmanaged',
      realPath,
      current,
      blocker: `${dest} exists but was not installed by warroom. Refusing to overwrite. Re-run with --force to adopt it (a backup is taken first).`,
    };
  }
  return { state: 'managed', blocker: null, realPath, current };
}

function backup(realPath, session) {
  const bytes = fs.readFileSync(realPath);
  const id = `${session}-${crypto.randomUUID()}`;
  const dir = path.join(BACKUPS, id);
  fs.mkdirSync(dir, { recursive: true });
  const stored = path.join(dir, path.basename(realPath));
  fs.writeFileSync(stored, bytes);
  return { id, stored, origin: realPath, sha256: sha256(bytes), bytes: bytes.length };
}

function cmdCheck(configs) {
  const m = readManifest();
  const installedProgram = path.join(WARROOM_HOME, 'bin', 'warroom');
  const srcHash = fs.existsSync(PROGRAM_SRC) ? sha256File(PROGRAM_SRC) : null;
  const liveHash = fs.existsSync(installedProgram) ? sha256File(installedProgram) : null;

  console.log('warroom check — READ-ONLY, nothing is written\n');
  console.log(`  repo program   bin/warroom            ${srcHash ? srcHash.slice(0, 12) : 'ABSENT'}`);
  console.log(`  installed      ~/.warroom/bin/warroom ${liveHash ? liveHash.slice(0, 12) : 'not installed'}`);
  if (srcHash && liveHash && srcHash !== liveHash) console.log('  ⚠ installed program differs from the repo copy — an update is pending');
  console.log('');

  const rows = [];
  for (const cfg of configs) {
    let c;
    try {
      c = readConfig(cfg);
    } catch (e) {
      rows.push({ session: path.basename(cfg), status: 'CONFIG UNREADABLE', projectDir: e.message });
      continue;
    }
    const rec = m.installs?.[c.session];
    const dest = path.join(HOME, 'bin', c.session);
    const i = inspect(dest, rec?.files?.[dest]?.sha256);
    rows.push({
      session: c.session,
      status: rec ? i.state : i.state === 'new' ? 'not installed' : 'standalone',
      projectDir: c.projectDir,
      projectOk: fs.existsSync(c.projectDir),
      blocker: i.blocker,
    });
  }

  const w = Math.max(...rows.map((r) => r.session.length), 7);
  console.log(`  ${'SESSION'.padEnd(w)}  ${'STATUS'.padEnd(14)}  PROJECT DIR`);
  for (const r of rows) {
    const flag = r.projectOk === false ? '  ⚠ project_dir missing' : '';
    console.log(`  ${r.session.padEnd(w)}  ${String(r.status).padEnd(14)}  ${r.projectDir || ''}${flag}`);
  }
  for (const r of rows.filter((x) => x.blocker)) console.log(`\n  ⚠ ${r.session}: ${r.blocker}`);
  console.log(`\n  ${rows.length} config(s) inspected. No files were written.`);
  return 0;
}

/**
 * Fleet scan — READ-ONLY. Reports every standalone launcher in ~/bin and which
 * generation it belongs to, without needing a config inside any project.
 *
 * Phase 2 is not permitted to write to any project except agentvibe, so the
 * cross-project inventory has to come from reading ~/bin directly. Generations
 * are computed exactly as the fleet baseline does: normalise each launcher for
 * its own name, then group by content hash.
 */
function cmdFleet(exclude) {
  const bin = path.join(HOME, 'bin');
  if (!fs.existsSync(bin)) {
    console.error(`✗ ${bin} does not exist`);
    return 1;
  }
  const launchers = fs
    .readdirSync(bin)
    .filter((f) => !f.includes('.bak'))
    .filter((f) => {
      const p = path.join(bin, f);
      try {
        return fs.statSync(p).isFile() && /CEO_PREAMBLE|CEO_SEED_FILE|CATO_PREAMBLE/.test(fs.readFileSync(p, 'utf8'));
      } catch {
        return false;
      }
    })
    .sort();

  const gens = new Map();
  const rows = launchers.map((name) => {
    const text = fs.readFileSync(path.join(bin, name), 'utf8');
    const norm = text.replace(new RegExp(name, 'gi'), '__P__');
    const h = sha256(norm).slice(0, 8);
    if (!gens.has(h)) gens.set(h, []);
    gens.get(h).push(name);
    const fns = new Set((norm.match(/^[a-z_][a-z0-9_]*\(\)/gm) || []));
    return { name, lines: text.split('\n').length, gen: h, fns: fns.size, excluded: exclude.includes(name) };
  });

  console.log('warroom fleet — READ-ONLY, nothing is written\n');
  const w = Math.max(...rows.map((r) => r.name.length), 8);
  console.log(`  ${'LAUNCHER'.padEnd(w)}  LINES  FN   GEN       SCOPE`);
  for (const r of rows) {
    console.log(
      `  ${r.name.padEnd(w)}  ${String(r.lines).padStart(5)}  ${String(r.fns).padStart(2)}   ${r.gen}  ${r.excluded ? 'excluded' : 'in scope'}`
    );
  }
  const inScope = rows.filter((r) => !r.excluded);
  const scopedGens = new Set(inScope.map((r) => r.gen));
  console.log(`\n  ${rows.length} launchers, ${gens.size} generations total`);
  console.log(`  ${inScope.length} in scope, ${scopedGens.size} generations in scope`);
  const fnSets = new Map();
  for (const r of inScope) fnSets.set(r.fns, (fnSets.get(r.fns) || 0) + 1);
  console.log(`  function-count spread in scope: ${[...fnSets.entries()].map(([k, v]) => `${k}fn x${v}`).join(', ')}`);
  console.log('\n  No files were written.');
  return 0;
}

function cmdInstall(configPath, force) {
  const c = readConfig(configPath);
  if (!c.session || !c.projectDir) {
    console.error(`✗ ${configPath} must define session and project_dir`);
    return 1;
  }
  if (!fs.existsSync(PROGRAM_SRC)) {
    console.error(`✗ program source missing: ${PROGRAM_SRC}`);
    return 1;
  }

  const m = readManifest();
  const rec = m.installs?.[c.session];
  const destProgram = path.join(WARROOM_HOME, 'bin', 'warroom');
  const destShim = path.join(HOME, 'bin', c.session);

  const plan = [
    { dest: destProgram, content: fs.readFileSync(PROGRAM_SRC), mode: 0o755, label: 'program' },
    { dest: destShim, content: Buffer.from(shimFor(c.session, c.file)), mode: 0o755, label: 'shim' },
  ];

  // ── Plan and refuse BEFORE writing anything (installation_modified guard).
  const blockers = [];
  for (const step of plan) {
    const i = inspect(step.dest, rec?.files?.[step.dest]?.sha256);
    step.inspect = i;
    if (i.blocker && !(force && i.state !== 'hardlink')) blockers.push(i.blocker);
  }
  if (blockers.length) {
    console.error(`✗ refusing to install ${c.session}:\n`);
    for (const b of blockers) console.error(`  - ${b}`);
    console.error('\n  Nothing was written.');
    return 1;
  }

  // ── Apply.
  const backups = [];
  const files = {};
  for (const step of plan) {
    const real = step.inspect.realPath;
    if (fs.existsSync(real)) backups.push(backup(real, c.session));
    fs.mkdirSync(path.dirname(real), { recursive: true });
    fs.writeFileSync(real, step.content);
    fs.chmodSync(real, step.mode);
    files[step.dest] = { sha256: sha256(step.content), label: step.label, realPath: real };
    console.log(`  ✓ ${step.label.padEnd(8)} ${step.dest}${real !== step.dest ? ` -> ${real}` : ''}`);
  }

  // ── Validate what we just wrote. A broken launcher means no session starts.
  try {
    execFileSync('bash', ['-n', destProgram], { stdio: 'pipe' });
    execFileSync('bash', ['-n', files[destShim].realPath], { stdio: 'pipe' });
  } catch (e) {
    console.error(`\n✗ syntax check FAILED after install: ${e.message}`);
    console.error('  Roll back with: node scripts/warroom-install.mjs rollback --session ' + c.session);
    return 1;
  }

  m.installs = m.installs || {};
  m.installs[c.session] = {
    config: c.file,
    projectDir: c.projectDir,
    installedAt: new Date().toISOString(),
    programSha256: sha256File(PROGRAM_SRC),
    files,
    backups,
  };
  writeManifest(m);

  console.log(`\n✓ ${c.session} installed. Backups: ${backups.length ? backups.map((b) => b.id).join(', ') : 'none needed'}`);
  console.log(`  Manifest: ${MANIFEST}`);
  return 0;
}

function cmdRollback(session) {
  const m = readManifest();
  const rec = m.installs?.[session];
  if (!rec) {
    console.error(`✗ no install recorded for "${session}" — nothing to roll back.`);
    return 1;
  }
  if (!rec.backups?.length) {
    console.error(`✗ install of "${session}" recorded no backups (it was a fresh install).`);
    console.error('  Remove the shim by hand if you want it gone; refusing to guess.');
    return 1;
  }
  // Fail loudly on a missing or altered backup rather than restoring garbage.
  for (const b of rec.backups) {
    if (!fs.existsSync(b.stored)) {
      console.error(`✗ backup missing: ${b.stored}`);
      console.error('  Refusing to roll back a partial set. Nothing was written.');
      return 1;
    }
    if (sha256File(b.stored) !== b.sha256) {
      console.error(`✗ backup corrupt: ${b.stored} (hash changed since it was taken)`);
      console.error('  Refusing to restore it. Nothing was written.');
      return 1;
    }
  }
  for (const b of rec.backups) {
    fs.copyFileSync(b.stored, b.origin);
    console.log(`  ✓ restored ${b.origin} from ${b.id}`);
  }
  delete m.installs[session];
  writeManifest(m);
  console.log(`\n✓ ${session} rolled back; ${rec.backups.length} file(s) restored.`);
  return 0;
}

// ── CLI ────────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const cmd = argv[0];
const force = argv.includes('--force');
const valuesOf = (flag) => argv.reduce((a, v, i) => (argv[i - 1] === flag ? [...a, v] : a), []);

// Excluded from Phase 2/9 scope by founder decision, 2026-08-11.
const EXCLUDED = ['adamos', 'test1', 'hitstampjavagame'];

let code = 0;
if (cmd === 'fleet') {
  code = cmdFleet(EXCLUDED);
} else if (cmd === 'check') {
  let configs = valuesOf('--config');
  if (!configs.length) configs = fs.existsSync(path.join(REPO, '.warroom.yml')) ? [path.join(REPO, '.warroom.yml')] : [];
  if (!configs.length) {
    console.error('✗ check: no --config given and no .warroom.yml in the repo root');
    code = 1;
  } else code = cmdCheck(configs);
} else if (cmd === 'install') {
  const cfg = valuesOf('--config')[0];
  if (!cfg) {
    console.error('✗ install requires --config <path>');
    code = 1;
  } else code = cmdInstall(cfg, force);
} else if (cmd === 'rollback') {
  const s = valuesOf('--session')[0];
  if (!s) {
    console.error('✗ rollback requires --session <name>');
    code = 1;
  } else code = cmdRollback(s);
} else {
  console.error('usage: warroom-install.mjs fleet|check|install|rollback [--config <path>] [--session <name>] [--force]');
  code = 1;
}
process.exit(code);
